// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oibmzhelqoxbskqyllhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYm16aGVscW94YnNrcXlsbGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzM1NzMsImV4cCI6MjA2Mzc0OTU3M30.CP2PfmDF_b5adggYBFyj-eY919na9DIcGbsnUkrFHBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);